#!/bin/bash

# Minecraft Discord Bot - Linux/Docker Installer
# ---------------------------------------------------
# This script handles:
# 1. Dependency checks (Docker, Git)
# 2. Environment configuration (.env)
# 3. Docker container deployment

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Ensure we are in the project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ "$(basename "$SCRIPT_DIR")" == "install" ]]; then
    cd "$(dirname "$SCRIPT_DIR")"
fi

echo -e "${CYAN}---------------------------------------------${NC}"
echo -e "${CYAN}   Minecraft Discord Bot - Linux Installer   ${NC}"
echo -e "${CYAN}---------------------------------------------${NC}"
echo ""

# 1. Check & Install Dependencies
echo -e "${BLUE}[1/4] Checking dependencies...${NC}"

if ! command -v git &> /dev/null; then
    echo -e "${YELLOW}[WARN] Git is not installed.${NC}"
    echo -e "${BLUE}Installing Git...${NC}"
    if command -v apt-get &> /dev/null; then
        sudo apt-get update && sudo apt-get install -y git
    elif command -v apk &> /dev/null; then
        sudo apk add git
    else
        echo -e "${RED}[ERROR] Could not install Git automatically. Please install it manually.${NC}"
        exit 1
    fi
fi

if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}[WARN] Docker is not installed.${NC}"
    read -p "      > Install Docker automatically? (y/N) " install_docker
    if [[ $install_docker =~ ^[Yy]$ ]]; then
        echo -e "${BLUE}Installing Docker (using official script)...${NC}"
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        rm get-docker.sh
        
        echo -e "${BLUE}Adding user $USER to docker group...${NC}"
        sudo usermod -aG docker $USER
        echo -e "${GREEN}[OK] Docker installed.${NC}"
        echo -e "${YELLOW}[IMPORTANT] You must log out and log back in for group changes to take effect.${NC}"
        echo -e "${YELLOW}            Please run this script again after re-login.${NC}"
        exit 0
    else
        echo -e "${RED}[ERROR] Docker is required.${NC}"
        exit 1
    fi
fi

# 2. Configure Environment
echo ""
echo -e "${BLUE}[2/4] Configuring Environment...${NC}"

if [ -f .env ]; then
    echo -e "${GREEN}[OK] .env file exists.${NC}"
    read -p "      > Reconfigure? (y/N) " reconfig
    if [[ ! $reconfig =~ ^[Yy]$ ]]; then
        SKIP_CONFIG=1
    fi
fi

if [ -z "$SKIP_CONFIG" ]; then
    # Discord Token
    echo ""
    echo -e "Enter your ${CYAN}Discord Bot Token${NC}:"
    echo -e "(Get it from https://discord.com/developers/applications)"
    read -p "> " BOT_TOKEN
    
    if [ -z "$BOT_TOKEN" ]; then
        echo -e "${RED}[ERROR] Token required.${NC}"
        exit 1
    fi

    # Playit.gg
    echo ""
    echo -e "Do you want to configure ${CYAN}Playit.gg${NC} for public access?"
    echo -e "(Requires a specific Secret Key from playit.gg -> Add Agent -> Linux/Docker)"
    read -p "> [y/N] " setup_playit
    
    PLAYIT_KEY=""
    if [[ $setup_playit =~ ^[Yy]$ ]]; then
        echo -e "Enter your ${CYAN}Playit Secret Key${NC}:"
        read -p "> " PLAYIT_KEY
    fi

    # Generate RCON
    RCON_PASSWORD=$(openssl rand -base64 24 | tr -d "=+/" | cut -c1-24)

    # Write .env
    cat > .env <<EOF
# Generated by install.sh
BOT_TOKEN=$BOT_TOKEN
RCON_PASSWORD=$RCON_PASSWORD
PLAYIT_SECRET_KEY=$PLAYIT_KEY
EOF
    echo -e "${GREEN}[OK] Configuration saved.${NC}"
fi

# 3. Create Directories
echo ""
echo -e "${BLUE}[3/4] Creating directories...${NC}"
mkdir -p mc-server backups logs
echo -e "${GREEN}[OK] Directories ready.${NC}"

# 4. Docker Compose Up
echo ""
echo -e "${BLUE}[4/4] Starting Services...${NC}"

# Detect compose command
if docker compose version &> /dev/null; then
    COMPOSE_CMD="docker compose"
elif command -v docker-compose &> /dev/null; then
    COMPOSE_CMD="docker-compose"
else
    echo -e "${RED}[ERROR] docker compose plugin not found.${NC}"
    exit 1
fi

echo -e "Building and starting containers..."
$COMPOSE_CMD up -d --build

echo ""
echo -e "${GREEN}---------------------------------------------${NC}"
echo -e "${GREEN}   Setup Complete!   ${NC}"
echo -e "${GREEN}---------------------------------------------${NC}"
echo ""
echo -e "Your bot should be online in Discord."
echo -e "Run: ${CYAN}/setup${NC} in Discord to initialize channels."
echo ""
echo -e "To view logs: ${CYAN}$COMPOSE_CMD logs -f mc-bot${NC}"
echo -e "To start tunnel: ${CYAN}$COMPOSE_CMD logs -f playit${NC} (if configured)"